### PR TITLE
Add tentative public server instructions

### PR DESCRIPTION
**Pull request by bobthebadguy**
Kinda short for some things tho

### CODE REVIEW

**Comment by Volas171** [comment]
very short tutorial

**Comment by Volas171** [comment]
well if it gets added I'll add more to the file lol

**Review by Volas171 — CHANGES_REQUESTED** [review]
add more explanatory stuff like how to open the firewall 6567 port lol

**Review by L0615T1C5-216AC-9437 — CHANGES_REQUESTED** [review]
> You will need to set it up to forward port 6567    

if this is a continuation for the local server then you need to specify to set the port to the same as the server they made

step 3 is confusing. Just get to the point. Make setting up ddns a separate thing

**Pull request closed without merging**
